<?php
namespace Admin\Controller;

use Common\Controller;

class IndexController extends Controller\AdminBaseController
{
    public $menu_mod;

    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub

        $this->menu_mod = D("Menu");
    }


    public function index()
    {
        $this->display();
    }
}
