<?php
/**
 * Created by PhpStorm.
 * User: shangbl
 * Date: 2016/3/23
 * Time: 6:00
 */

namespace Admin\Controller;

use Common\Controller;

class MenuController extends Controller\AdminBaseController
{
    public $mod = "";

    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub

        $this->mod = M("Menu");
    }


    public function index()
    {
        $lists = $this->mod->select();
        $this->assign("lists", $lists);
        $this->display();
    }
}